// حالات الموضوع — PRD §9 / TDD §4.1
export const TopicStatus = {
  DRAFT: 'DRAFT',
  PENDING_DEPT_MGR: 'PENDING_DEPT_MGR',
  APPROVED: 'APPROVED',
  SENT_TO_GS: 'SENT_TO_GS',
  INBOX_GS: 'INBOX_GS',
  GS_REVIEW: 'GS_REVIEW',
  SUSPENDED: 'SUSPENDED',
  RETURNED_DEPT: 'RETURNED_DEPT',
  CLOSED_BY_DEPT: 'CLOSED_BY_DEPT',
  WITH_COUNCIL: 'WITH_COUNCIL',
  EXAM_IN_PROGRESS: 'EXAM_IN_PROGRESS',
  EXAM_COMPLETE: 'EXAM_COMPLETE',
  EXAM_INCOMPLETE: 'EXAM_INCOMPLETE',
  PRESIDENT_REVIEW: 'PRESIDENT_REVIEW',
  RETURNED_COUNCIL: 'RETURNED_COUNCIL',
  IN_AGENDA_BOX: 'IN_AGENDA_BOX',
  LINKED_TO_MEETING: 'LINKED_TO_MEETING',
  DEFERRED_IN_SESSION: 'DEFERRED_IN_SESSION',
  DISCUSSED: 'DISCUSSED',
  DECISION_PENDING: 'DECISION_PENDING',
  DECISION_ISSUED: 'DECISION_ISSUED',
  NOTIFIED: 'NOTIFIED',
} as const;

// إجراءات الانتقال
export const TopicAction = {
  SUBMIT_TO_MANAGER: 'SUBMIT_TO_MANAGER',
  APPROVE: 'APPROVE',
  RETURN_TO_DRAFT: 'RETURN_TO_DRAFT',
  REVOKE_APPROVAL: 'REVOKE_APPROVAL',
  SEND_TO_GS: 'SEND_TO_GS',
  ACCEPT: 'ACCEPT',
  SUSPEND: 'SUSPEND',
  RESUME: 'RESUME',
  REJECT: 'REJECT',
  RETURN_WRONG_COUNCIL: 'RETURN_WRONG_COUNCIL',
  RESUBMIT: 'RESUBMIT',
  CLOSE_BY_DEPT: 'CLOSE_BY_DEPT',
  ASSIGN_EXAM: 'ASSIGN_EXAM',
  EXAM_PASS: 'EXAM_PASS',
  EXAM_FAIL: 'EXAM_FAIL',
  REEXAM: 'REEXAM',
  SUBMIT_TO_PRESIDENT: 'SUBMIT_TO_PRESIDENT',
  MARK_SUITABLE: 'MARK_SUITABLE',
  RETURN_TO_COUNCIL: 'RETURN_TO_COUNCIL',
  LINK_TO_MEETING: 'LINK_TO_MEETING',
  WITHDRAW_FROM_MEETING: 'WITHDRAW_FROM_MEETING',
  DEFER_IN_SESSION: 'DEFER_IN_SESSION',
  MARK_DISCUSSED: 'MARK_DISCUSSED',
} as const;

// حالات الاجتماع
export const MeetingStatus = {
  MEETING_DRAFT_SEC: 'MEETING_DRAFT_SEC',
  MEETING_GS_APPROVAL: 'MEETING_GS_APPROVAL',
  MEETING_BACK_SEC: 'MEETING_BACK_SEC',
  MEETING_PRES_APPROVAL: 'MEETING_PRES_APPROVAL',
  MEETING_SCHEDULED: 'MEETING_SCHEDULED',
  MEETING_HELD: 'MEETING_HELD',
  MEETING_ADJOURNED: 'MEETING_ADJOURNED',
  MEETING_CANCELLED: 'MEETING_CANCELLED',
} as const;

// حالات المحضر
export const MinutesStatus = {
  MIN_DRAFT: 'MIN_DRAFT',
  MIN_GS_REVIEW: 'MIN_GS_REVIEW',
  MIN_GS_RETURNED: 'MIN_GS_RETURNED',
  MIN_MEMBERS_CONSULT: 'MIN_MEMBERS_CONSULT',
  MIN_TO_PRESIDENT: 'MIN_TO_PRESIDENT',
  MIN_PRES_REJECT: 'MIN_PRES_REJECT',
  MIN_SIGNED: 'MIN_SIGNED',
} as const;

// حالات القرار
export const DecisionStatus = {
  DEC_DRAFT: 'DEC_DRAFT',
  DEC_ISSUED: 'DEC_ISSUED',
} as const;

// حالات التبليغ
export const NotifStatus = {
  NOTIF_PENDING: 'NOTIF_PENDING',
  NOTIF_DONE: 'NOTIF_DONE',
  NOTIF_FAIL: 'NOTIF_FAIL',
} as const;

// حالات التفويض
export const DelegationState = {
  DELEGATION_DRAFT: 'DELEGATION_DRAFT',
  PENDING_ACTIVATION: 'PENDING_ACTIVATION',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  EXPIRED: 'EXPIRED',
  REVOKED: 'REVOKED',
  SUPERSEDED: 'SUPERSEDED',
} as const;

// أكواد الأدوار
export const RoleCode = {
  DEPT_STAFF: 'DEPT_STAFF',
  DEPT_MANAGER: 'DEPT_MANAGER',
  GENERAL_SECRETARY: 'GENERAL_SECRETARY',
  GS_OFFICE_STAFF: 'GS_OFFICE_STAFF',
  COUNCIL_SECRETARY: 'COUNCIL_SECRETARY',
  EXAM_OFFICER: 'EXAM_OFFICER',
  COUNCIL_PRESIDENT: 'COUNCIL_PRESIDENT',
  COUNCIL_MEMBER: 'COUNCIL_MEMBER',
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
} as const;
